### ISSUE TITLE
Puppeteer error thrown when offline

### ISSUE THREAD

**Issue by michaeltoohig** [JulianCataldo/web-garden#43]
So I don't know much about puppeteer but the error seems to be it will not work without internet access. Returning internet access then restarting the dev server and the mermaid charts would work again.

This issue may not be related to your project since the error seems to originate from Puppeteer but I just wanted to verify this behavior is expected.

```
05:53:34 PM [astro] reload /src/pages/project/remote-video-monitoring/index.mdx (x4)julian_cataldo/astro-diagram/dist/index.js:38:9)
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'initialize')
    at __puppeteer_evaluation_script__:2:24
    at ExecutionContext._evaluateInternal (/home/michael/projects/astro-website/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/michael/projects/astro-website/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Object.execute (/home/michael/projects/astro-website/node_modules/headless-mermaid/index.js:28:20)
    at async $4caa44378d385ef8$export$2e2bcd8739ae039 (file:///home/michael/projects/astro-website/node_modules/@julian_cataldo/astro-diagram/dist/index.js:7:59)
    at async file:///home/michael/projects/astro-website/node_modules/@julian_cataldo/astro-diagram/dist/index.js:43:26
    at async Promise.all (index 0)
    at async transformer (file:///home/michael/projects/astro-website/node_modules/@julian_cataldo/astro-diagram/dist/index.js:38:9)
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'initialize')
    at __puppeteer_evaluation_script__:2:24
    at ExecutionContext._evaluateInternal (/home/michael/projects/astro-website/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/michael/projects/astro-website/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Object.execute (/home/michael/projects/astro-website/node_modules/headless-mermaid/index.js:28:20)
    at async $4caa44378d385ef8$export$2e2bcd8739ae039 (file:///home/michael/projects/astro-website/node_modules/@julian_cataldo/astro-diagram/dist/index.js:7:59)
    at async file:///home/michael/projects/astro-website/node_modules/@julian_cataldo/astro-diagram/dist/index.js:43:26
    at async Promise.all (index 1)
    at async transformer (file:///home/michael/projects/astro-website/node_modules/@julian_cataldo/astro-diagram/dist/index.js:38:9)
```

Thank you.

**Comment by JulianCataldo** [comment]
Hello there,

You're right,
`astro-diagram` relies on `headless-mermaid` which is importing the `mermaid` library from a CDN.

https://github.com/muhammadmuzzammil1998/headless-mermaid/blob/master/index.js

I will try something for using offline / Node package import instead.

Thanks for your feedback

**Comment by JulianCataldo** [comment]
Fixed!
https://github.com/JulianCataldo/web-garden/commit/e480f9fadb62705e174461527151002925f78858
